project:
  type: website

website:
  title: "Harpreet_portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: "Resume"
      - href: Projects name.qmd
        text: "Projects"
      - href: skills.qmd
        text: "Skills & Certifications"
      - href: contact.qmd
        text: "Contact Me"
      
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



